use [DHCM]

insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('A69.0',' NECROTIZING ULCERATIVE STOMATITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('A69.1',' OTHER VINCENT''S INFECTIONS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('B00.2',' HERPESVIRAL GINGIVOSTOMATITIS AND PHARYNGOTONSILLI',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('B00.9',' HERPESVIRAL INFECTION: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('B37.0',' CANDIDAL STOMATITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('B37.9',' CANDIDIASIS: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('C80.1',' MALIGNANT (PRIMARY) NEOPLASM: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('G43.909','MIGRAINE: UNSPECIFIED: NOT INTRACTABLE: WITHOUT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('G47.63',' BRUXISM, SLEEP RELATED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('G89.29',' OTHER CHRONIC PAIN',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('J32.9',' CHRONIC SINUSTIS: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.0',' ANODONTIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.1',' SUPERNUMERARY TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.2',' ABNORMALITIES OF SIZE AND FORM OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.3',' MOTTLED TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.4',' DISTURBANCES OF TOOTH FORMATION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.5',' HEREDITARY DISTURBANCES IN TOOTH STRUCTURE NOT ELSEWHERE CLASSIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.6',' DISTURBANCES IN TOOTH ERUPTION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.7',' TEETHING SYNDROME',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.8',' OTHER SPECIFIED DISORDERS OF TOOTH DEVELOPMENT AND ERUPTION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K00.9',' UNSPECIFIED DISORDER OF TOOTH DEVELOPMENT AND ERUPTION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K01.0',' EMBEDDED TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K01.1',' IMPACTED TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.3',' ARRESTED DENTAL CARIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.5',' DENTAL CARIES ON PIT AND FISSURE SURFACE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.51',' DENTAL CARIES ON PIT AND FISSURE SURFACE LIMITED TO ENAMEL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.52',' DENTAL CARIES ON PIT AND FISSURE SURFACE PENETRATING INTO DENTIN',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.53',' DENTAL CARIES ON PIT AND FISSURE SURFACE PENETRATING INTO PULP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.6',' DENTAL CARIES ON SMOOTH SURFACE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.61',' DENTAL CARIES ON SMOOTH SURFACE LIMITED TO ENAMEL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.62',' DENTAL CARIES ON SMOOTH SURFACE PENETRATING INTO DENTIN',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.63',' DENTAL CARIES ON SMOOTH SURFACE PENETRATING INTO PULP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.7',' DENTAL ROOT CARIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K02.9',' UNSPECIFIED DENTAL CARIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.0',' EXCESSIVE ATTRITION OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.1',' ABRASION OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.2',' EROSION OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.3',' PATHOLOGICAL RESORPTION OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.4',' HYPERCEMENTOSIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.5',' ANKYLOSIS OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.6',' DEPOSITS ON TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.7',' POSTERUPTIVE COLOR CHANGES OF DENTAL HARD TISSUES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.8',' OTHER SPECIFIED DISEASES OF HARD TISSUES OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.81',' CRACKED TOOTH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.89',' OTHER SPECIFIED DISEASES OF HARD TISSUES OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K03.9',' UNSPECIFIED DISEASE OF HARD TISSUES OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.0',' PULPITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.01',' REVERSIBLE PULPITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.02',' IRREVERSIBLE PULPITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.1',' NECROSIS OF THE PULP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.2',' PULP DEGENERATION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.3',' ABNORMAL HARD TISSUE FORMATION IN PULP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.4',' ACUTE APICAL PERIODONTITIS OF PULPAL ORIGIN',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.5',' CHRONIC APICAL PERIODONTITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.6',' PERIAPICAL ABSCESS WITH SINUS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.7',' PERIAPICAL ABSCESS WITHOUT SINUS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.8',' RADICULAR CYST',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.9',' OTHER AND UNSPECIFIED LESIONS OF ORAL MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.90',' UNSPECIFIED DISEASES OF PULP AND PERIAPICAL TISSUES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K04.99',' OTHER DISEASES OF PULP AND PERIAPICAL TISSUES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.0',' ACUTE GINGIVITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.00',' ACUTE GINGIVITIS, PLAQUE INDUCED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.01',' ACUTE GINGIVITIS, NON-PLAQUE INDUCED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.1',' CHRONIC GINGIVITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.10',' CHRONIC GINGIVITIS, PLAQUE INDUCED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.11',' CHRONIC GINGIVITIS, NON-PLAQUE INDUCED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.2',' AGGRESSIVE PERIODONTITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.20',' UNSPECIFIED AGGRESSIVE PERIODONTITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.21',' AGGRESSIVE PERIODONTITIS, LOCALIZED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.221',' AGGRESSIVE PERIODONTITIS, GENERALIZED, SLIGHT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.222',' AGGRESSIVE PERIODONTITIS, GENERALIZED, MODERATE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.223',' AGGRESSIVE PERIODONTITIS, GENERALIZED, SEVERE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.3',' CHRONIC PERIODONTITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.30',' CHRONIC PERIODONTITIS, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.311',' CHRONIC PERIODONTITIS, LOCALIZED, SLIGHT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.312',' CHRONIC PERIODONTITIS, LOCALIZED, MODERATE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.313',' CHRONIC PERIODONTITIS, LOCALIZED, SEVERE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.319',' CHRONIC PERIODONTITIS, LOCALIZED, UNSPECIFIED SEVERITY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.321',' CHRONIC PERIODONTITIS, GENERALIZED, SLIGHT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.322',' CHRONIC PERIODONTITIS, GENERALIZED, MODERATE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.323',' CHRONIC PERIODONTITIS, GENERALIZED, SEVERE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.329',' CHRONIC PERIODONTITIS, GENERALIZED, UNSPECIFIED SEVERITY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.4',' PERIODONTOSIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.5',' OTHER PERIODONTAL DISEASES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K05.6',' UNSPECIFIED PERIODONTAL DISEASE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K06.0',' GINGIVAL RECESSION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K06.1',' GINGIVAL ENLARGEMENT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K06.2',' GINGIVAL AND EDENTULOUS ALVEOLAR RIDGE LESIONS ASSOCIATED WITH TRAUMA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K06.8',' OTHER SPECIFIED DISORDERS OF GINGIVA AND EDENTULOUS ALEVOLAR RIDGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K06.9',' DISORDER OF GINGIVA AND EDENTULOUS ALVEOLAR RIDGE, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.0',' EXFOLIATION OF TEETH DUE TO SYSTEMIC CAUSES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.1',' COMPLETE LOSS OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.10',' COMPLETE LOSS OF TEETH, UNSPECIFIC CAUSE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.101',' COMPLETE LOSS OF TEETH, UNSPECIFIC CAUSE, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.102',' COMPLETE LOSS OF TEETH, UNSPECIFIC CAUSE, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.103',' COMPLETE LOSS OF TEETH, UNSPECIFIC CAUSE, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.104',' COMPLETE LOSS OF TEETH, UNSPECIFIC CAUSE, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.109',' COMPLETE LOSS OF TEETH, UNSPECIFIC CAUSE, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.11',' COMPLETE LOSS OF TEETH DUE TO TRAUMA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.111',' COMPLETE LOSS OF TEETH DUE TO TRAUMA, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.112',' COMPLETE LOSS OF TEETH DUE TO TRAUMA, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.113',' COMPLETE LOSS OF TEETH DUE TO TRAUMA, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.114',' COMPLETE LOSS OF TEETH DUE TO TRAUMA, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.119',' COMPLETE LOSS OF TEETH DUE TO TRAUMA, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.191',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.12',' COMPLETE LOSS OF TEETH DUE TO PERIODONTAL DISEASE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.121',' COMPLETE LOSS OF TEETH DUE TO PERIODONTAL DISEASE, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.122',' COMPLETE LOSS OF TEETH DUE TO PERIODONTAL DISEASE, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.123',' COMPLETE LOSS OF TEETH DUE TO PERIODONTAL DISEASE, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.124',' COMPLETE LOSS OF TEETH DUE TO PERIODONTAL DISEASE, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.129',' COMPLETE LOSS OF TEETH DUE TO PERIODONTAL DISEASE, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.191',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.13',' COMPLETE LOSS OF TEETH DUE TO CARIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.131',' COMPLETE LOSS OF TEETH DUE TO CARIES, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.132',' COMPLETE LOSS OF TEETH DUE TO CARIES, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.133',' COMPLETE LOSS OF TEETH DUE TO CARIES, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.134',' COMPLETE LOSS OF TEETH DUE TO CARIES, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.139',' COMPLETE LOSS OF TEETH DUE TO CARIES, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.19',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.191',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.192',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.193',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.194',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.199',' COMPLETE LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.2',' ATROPHY OF EDENTULOUS ALEVEOLAR RIDGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.20',' UNSPECIFIED ATROPHY OF EDENTULOUS ALVEOLAR RIDGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.21',' MINIMAL ATROPHY OF THE MANDIBLE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.22',' MODERATE ATROPHY OF THE MANDIBLE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.23',' SEVERE ATROPHY OF THE MANDIBLE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.24',' MINIMAL ATROPHY OF THE MAXILLA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.25',' MODERATE ATROPHY OF THE MAXILLA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.26',' SEVERE ATROPHY OF THE MAXILLA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.3',' RETAINED DENTAL ROOT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.4',' PARTIAL LOSS OF TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.40',' PARTIAL LOSS OF TEETH, UNSPECIFIED CAUSE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.401',' PARTIAL LOSS OF TEETH, UNSPECIFIED CAUSE, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.402',' PARTIAL LOSS OF TEETH, UNSPECIFIED CAUSE, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.403',' PARTIAL LOSS OF TEETH, UNSPECIFIED CAUSE, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.404',' PARTIAL LOSS OF TEETH, UNSPECIFIED CAUSE, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.409',' PARTIAL LOSS OF TEETH, UNSPECIFIED CAUSE, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.41',' PARTIAL LOSS OF TEETH DUE TO TRAUMA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.411',' PARTIAL LOSS OF TEETH DUE TO TRAUMA, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.412',' PARTIAL LOSS OF TEETH DUE TO TRAUMA, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.413',' PARTIAL LOSS OF TEETH DUE TO TRAUMA, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.414',' PARTIAL LOSS OF TEETH DUE TO TRAUMA, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.419',' PARTIAL LOSS OF TEETH DUE TO TRAUMA, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.42',' PARTIAL LOSS OF TEETH DUE TO PERIODONTAL DISEASES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.421',' PARTIAL LOSS OF TEETH DUE TO PERIODONTAL DISEASES, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.422',' PARTIAL LOSS OF TEETH DUE TO PERIODONTAL DISEASES, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.423',' PARTIAL LOSS OF TEETH DUE TO PERIODONTAL DISEASES, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.424',' PARTIAL LOSS OF TEETH DUE TO PERIODONTAL DISEASES, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.429',' PARTIAL LOSS OF TEETH DUE TO PERIODONTAL DISEASES, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.43',' PARTIAL LOSS OF TEETH DUE TO CARIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.431',' PARTIAL LOSS OF TEETH DUE TO CARIES, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.432',' PARTIAL LOSS OF TEETH DUE TO CARIES, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.433',' PARTIAL LOSS OF TEETH DUE TO CARIES, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.434',' PARTIAL LOSS OF TEETH DUE TO CARIES, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.439',' PARTIAL LOSS OF TEETH DUE TO CARIES, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.49',' PARTIAL LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.491',' PARTIAL LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.492',' PARTIAL LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.493',' PARTIAL LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.494',' PARTIAL LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, CLASS IV',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.499',' PARTIAL LOSS OF TEETH DUE TO OTHER SPECIFIED CAUSE, UNSPECIFIED CLASS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.5',' UNSATISFACTORY RESTORATION OF TOOTH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.50',' UNSATISFACTORY RESTORATION OF TOOTH, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.51',' OPEN RESTORATION MARGINS OF TOOTH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.52',' UNREPAIRABLE OVERHANGING OF DENTAL RESTORATIVE MATERIALS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.53',' FRACTURED DENTAL RESTORATIVE MATERIAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.530',' FRACTURED DENTAL RESTORATIVE MATERIAL WITHOUT LOSS OF MATERIAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.531',' FRACTURED DENTAL RESTORATIVE MATERIAL WITH LOSS OF MATERIAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.539',' FRACTURED DENTAL RESTORATIVE MATERIAL, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.54',' CONTOUR OF EXISTING RESTORATION OF TOOTH BIOLOGICALLY INCOMPATIBLE   WITH ORAL HEALTH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.55',' ALLERGY TO EXISTING DENTAL RESTORATIVE MATERIAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.56',' POOR AESTHETICS OF EXISTING RESTORATION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.59',' OTHER UNSATISFACTORY RESTORATION OF EXISTING TOOTH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.8',' OTHER SPECIFIED DISORDERS OF TEETH AND SUPPORTING STRUCTURES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K08.9',' DISORDER OF TEETH AND SUPPORTING STRUCTURES, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K09.0',' DEVELOPMENTAL ODONTOGENIC CYSTS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K09.1',' DEVELOPMENTAL, NONODONTOGENIC, CYSTS OF ORAL REGION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K09.8',' OTHER CYSTS OF ORAL REGION, NOT ELSEWHERE CLASSIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K09.9',' CYST OF ORAL REGION, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K11.6',' MUCOCELE OF SALIVARY GLAND',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K11.7',' DISTURBANCE OF SALIVARY SECRETION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K11.8',' OTHER SPECIFIED DISEASES OF THE SALIVARY GLANDS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.0',' RECURRENT ORAL APHTHAE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.139',' OTHER ORAL MUCISITIS (ULCERATIVE)',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.2',' CELLULITIS AND ABSCESS OF MOUTH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.3',' ORAL MUCOSITIS (ULCERATIVE)',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.30',' ORAL MUCOSITIS (ULCERATIVE), UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.31',' ORAL MUCOSITIS (ULCERATIVE), DUE TO ANTINEOPLASTIC THERAPY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.32',' ORAL MUCOSITIS (ULCERATIVE) DUE TO OTHER DRUGS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.33',' ORAL MUCOSITIS (ULCERATIVE) DUE TO RADIATION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K12.39',' OTHER ORAL MUCOSITIS (ULCERATIVE)',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.0',' DISEASES OF LIPS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.1',' CHEEK AND LIP BITING',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.2',' TOUNGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.21',' LEUKOPLAKIA OF ORAL MUCOSA, INCLUDING TOUNGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.22',' MINIMAL KERATINIZED RESIDUAL RIDGE MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.23',' EXCESSIVE KERATINIZED RESIDUAL RIDGE MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.24',' LEUKOKERATOSIS NICOTINA PALATI',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.29',' OTHER DISTURBANCES OF ORAL EPITHELIUM, INCLUDING TOUNGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.3',' HAIRY LEUKOPLAKIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.4',' GRANULOMA AND GRANULOMA-LIKE LESIONS OF ORAL MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.5',' ORAL SUBMUCOSAL FIBROSIS INCLUDING OF TONGUE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.6',' IRRITATIVE HYPERPLASIA OF ORAL MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.7',' OTHER AND UNSPECIFIED LESIONS OF ORAL MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.70',' UNSPECIFIED LESIONS OF ORAL MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K13.79',' OTHER LESIONS OF ORAL MUCOSA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.0',' GLOSSITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.1',' GEOGRAPHIC TOUNGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.2',' MEDIAN RHOMBOID GLOSSITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.3',' HYPERTROPHY OF TOUNGE PAPILLAE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.4',' ATROPHY OF TOUNGE PAPILLAE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.5',' PLICATED TOUNGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.6',' GLOSSODYNIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.8',' OTHER DISEASES OF TOUNGE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K14.9',' DISEASE OF TOUNGE, UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K20.0',' EOSINOPHILIC ESOPHAGITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('K20.8',' OTHER ESOPHAGITIS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('L03.90',' CELLULITIS: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.00',' MAJOR ABNORMILITIES OF JAW SIZE, UNSPECIFIED ANOMALY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.01',' MAXILLARY HYPERPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.02',' MAXILLARY HYPOPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.03',' MANDIBULAR HYPERPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.04',' MANDIBULAR HYPOPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.07',' EXCESSIVE TUBEROSITY OF JAW',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.09',' OTHER SPECIFIED ANOMALIES OF JAW SIZE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.10',' UNSPECIFIED ANOMALY OF JAW-CRANIAL BASE RELATIONSHIP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.11',' MAXILLARY ASYMMETRY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.12',' OTHER JAW ASYMMETRY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.19',' OTHER SPECIFIED ANOMALIES OF JAW -CRANIAL BASE RELATIONSHIP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.20',' UNSPECIFIED ANOMALY OF DENTAL ARCH RELATIONSHIP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.211',' MALOCCLUSION: ANGLE''S CLASS I',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.212',' MALOCCLUSION: ANGLE''S CLASS II',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.213',' MALOCCLUSION: ANGLE''S CLASS III',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.220',' OPEN ANTERIOR OCCLUSAL RELATIONSHIP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.221',' OPEN POSTERIOR OCCLUSAL RELATIONSHIP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.23',' EXCESSIVE HORONONTAL OVERLAP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.24',' REVERSE ARTICULATION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.25',' ANOMALIES OF INTERARCH DISTANCE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.29',' OTHER ANOMALIES OF DENTAL ARCH RELATIONSHIP',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.30',' UNSPECIFIED ANOMALY OF TOOTH POSITION OF FULLY ERUP.',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.31',' CROWDING OF FULLY ERUPTED TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.32',' EXCESSIVE SPACING OF FULLY ERUPTED TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.33',' HORIZONTAL DISPLACEMENT OF FULLY ERUPTED TOOTH OR TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.34',' VERTICAL DISPLACEMENT OF FULLY ERUPTED TOOTH OR TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.35',' ROTATION OF FULLY ERUPTED TOOTH OR TEETH',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.36',' INSUFFICIENT INTEROCCLUSAL DISTANCE OF FULLY ERUPT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.37',' EXCESSIVE INTEROCCLUSAL DISTANCE OF FULLY ERUPTED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.39',' OTHER ANOMALIES OF TOOTH POSITION OF FULLY ERUPTED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.4',' MALOCCLUSION: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.60',' TEMPOROMANDIBULAR JOINT DISORDER: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.61',' ADHESIONS AND ANKYLOSIS OF TEMPOROMANDIBULAR JOINT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.62',' ARTHRALGIA OF TEMPOROMANDIBULAR JOINT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.63',' ARTICULAR DISC DISORDER OF TEMPOROMANDIBULAR JOINT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.69',' OTHER SPCIFIED DISORDERS OF TEMPOROMANDIBULAR JOINT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.7',' UNSPECIFIED ALVEOLAR ANOMALY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.71',' ALVEOLAR MAXILLARY HYPERPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.72',' ALVEOLAR MANDIBULAR HYERPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.73',' ALVEOLAR MAXILLARY HYPOPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.74',' ALVEOLAR MANDIBULAR HYPOPLASIA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.79',' OTHER SPECIFIED ALVEOLAR ANOMALIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.81',' ANTERIOR SOFT TISSUE IMPINGEMENT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.82',' POSTERIOR SOFT TISSUE IMPINGEMENT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.89',' OTHER DENTOFACIAL ANOMALIES',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M26.9',' DENTOFACIAL ANOMALY: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.1',' GIANT CELL GRANULOMA CENTRAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.2',' INFLAMMATORY CONDITIONS OF JAWS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.3',' ALVEOLITIS OF JAWS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.4',' OTHER CYSTS OF JAW',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.5',' PERFORATION OF ROOT CANAL SPACE DUE TO ENDODONTIC',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.52',' ENDODONTIC OVERFILL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.53',' ENDODONTIC UNDERFILL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.59',' OTHER PERIRADICULAR PATHOLOGY ASSOCIATED W/ PREVIOUS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.61',' OSSEOINTEGRATION FAILURE OF DENTAL IMPLANT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.62',' POST-OSSEOINTEGRATION BIOLOGICAL FAILURE OF IMPLANT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.63',' POST-OSSEOINTEGRATION MECHANICAL FAILURE OF IMPLANT',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.69',' OTHER ENDOSSEOUS DENTAL IMPLANT FAILURE',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.8',' OTHER SPECIFIED DISEASES OF JAWS',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M27.9',' DISEASE OF JAWS: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('M86.9',' OSTEOMYELITIS: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('Q36.9',' CLEFT LIP: UNILATERAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S01.512A',' LACERATION WITHOUT FOREIGN BODY OF ORAL CAVITY',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S01.54A',' PUNCTURE WOUND WITH FOREIGH BODY OF LIP: INITIAL',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S02.5XXA',' FRACT OF TH (TRAUMATIC): INITIAL ENCOUNTER CLOSED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S02.5XXB',' FRACT OF TH (TRAUMATIC): INITIAL ENCOUNTER OPEN',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S02.5XXD',' SUBSEQUENT ENCOUNTER FRACTURE TH, ROUTINE HEALING',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S02.5XXG',' SUBSEQUENT ENCOUNTER FRACTURE TH, DELAYED HEALING',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S02.5XXK',' SUBSEQUENT ENCOUNTER FRACTURE TH, NONUNION',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S03.2XXA',' DISLOCATION OF TOOTH: INITIAL ENCOUNTER',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S03.2XXD',' DISLOCATION OF TOOTH: SUBSEQUENT ENCOUNTER',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S03.2XXS',' DISLOCAION OF TOOTH: SEQUELA',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S09.90XA',' UNSPECIFIED INJURY OF HEAD: INITIAL ENCOUNTER',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('S09.93XA',' UNSPECIFIED INJURY OF FACE: INITIAL ENCOUNTER',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('T14.90',' INJURY: UNSPECIFIED',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('T18.0XXA',' FOREIGN BODY IN MOUTH: INITIAL ENCOUNTER',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('T65.294A',' TOXIC EFFECT OF OTHER TOBACCO AND NICOTINE: UNDET',1)
insert into Diagnosis_Mf (DiagnosisCode,DiagnosisName,IsActive) values('T81.4XXA',' INFECTION FOLLOWING A PROCEDURE: INITIAL ENCOUNTER',1)


